export const homepageCopy = {
  brand: {
    wordmark: "LightRain",
    engraveTagline: "Société de liquidité décentralisée",
  },
  ouverture: {
    sectionId: "section-ouverture",
    headingId: "heading-ouverture",
    eyebrow: "§ 01 — Ouverture",
    headline: {
      line1: "La liquidité, instantanée.",
      line2: "The speed of liquidity.",
      line3: "The permanence of credit.",
      line4: "The singularity of execution.",
      dropCap: "L",
    },
    body:
      "LightRain is a decentralized execution and credit abstraction protocol on Base. Atomic flash liquidity from Aave-grade pools, durable collateralized credit from a reputation-weighted vault, and a strategy router that composes the two into a single transaction. Built for the institutions for whom milliseconds are currency and reconciliation is non-negotiable.",
    primaryCta: { label: "Lire le protocole →", href: "/endowments#section-these" },
    heroBand: {
      card: {
        greeting: "Welcome Back",
        subtitle: "Sign on to manage your positions and your credit lines.",
        usernameLabel: "Email",
        passwordLabel: "Password",
        signOn: "Sign On",
        enroll: "Create An Account",
        showPassword: "Show",
        footer: [
          { label: "SSO with BlackLetter", href: "/#access" },
          { label: "Forgot username or password", href: "/#access" },
        ],
      },
      applyOfferColumn: {
        emailSection: {
          title: "LedgerBranch",
          bulletEm: "Identity Encryption",
          bulletRest:
            " — End-to-end protection for attestations and session-bound keys",
          primaryCta: { label: "Enrollment", href: "/#access" },
          body:
            "We'll email you a secure link to establish your account. Identity encryption is enabled once you complete the flow. Your recovery signers are configured immediately.",
        },
        smsSection: {
          title: "BlackLetter",
          bulletEm: "Account & Signature Sign On Services",
          bulletRest:
            "Policy-governed credential posture: attestation-brokered access and sign-on.",
          submitLabel: "Application",
          consent:
            "Generate cryptographic signatures tied to your attestation. Each application login is a verified signature request. Your keys never leave your control.",
        },
      },
    },
    statsStrip: [
      { label: "NOTIONNEL TRAITÉ", value: "$1.84 Md" },
      { label: "LIGNES DE CRÉDIT", value: "1 207" },
      { label: "EXÉCUTION MOYENNE", value: "214 ms" },
      { label: "COUVERTURE", value: "Base · L2" },
      { label: "ANCRAGE", value: "Coinbase" },
    ],
  },
  these: {
    sectionId: "section-these",
    headingId: "heading-these",
    eyebrow: "§ 02 — Thèse · what LightRain is",
    headline: "Two capital regimes. One execution surface.",
    columns: {
      left: [
        {
          lead: "Flash liquidity is ",
          em: "atomic",
          rest: ". Capital is issued, deployed, and repaid within a single transaction. The chain is the enforcement layer. Default is mathematically impossible; the trust surface is zero.",
        },
        {
          lead: "Credit is ",
          em: "durable",
          rest: ". Capital lives across hours, days, months. Collateral, reputation, and counterparty governance carry the risk. Enforcement is statistical, layered, and surveilled.",
        },
        {
          text: "Most protocols pick one. LightRain composes both into a single router, exposing them through one API, one strategy graph, one settlement layer.",
        },
        {
          text: "The thesis is that institutions do not want a flash-loan pool or a lending market. They want a programmable capital surface, and a counterparty that can reconcile every basis point of it on demand.",
        },
      ],
    },
    citation: {
      quote: "« Le métier n'est pas de prêter. Le métier est de réconcilier. »",
      attribution: "LightRain, note d'intention",
    },
  },
  flashCredit: {
    sectionId: "section-pratique",
    headingId: "heading-pratique",
    eyebrow: "§ 03 — Pratique · the two primitives",
    headline: "Flash and credit, drawn in elevation.",
    bridge:
      "One stack offers the same router, the same strategy graph, and the same reconciliation pipeline regardless of which side the capital came from.",
    flash: {
      label: "FLASH · atomique",
      annotation: "t = 1 bloc",
      specs: [
        { label: "LIQUIDITÉ", value: "Aave v3 · $1.82 Md" },
        { label: "FRAIS", value: "9 + 3 bps" },
        { label: "LATENCE", value: "214 ms" },
        { label: "DÉFAUT", value: "impossible" },
      ],
    },
    credit: {
      label: "CRÉDIT · durable",
      specs: [
        { label: "COLLATÉRAL", value: "tier I · WBTC · WETH · USDC" },
        { label: "SEUIL", value: "85% liquidation" },
        { label: "RÉPUTATION", value: "oracle pondéré" },
        { label: "INTÉRÊT", value: "variable, modèle SNOW" },
      ],
    },
  },
  execution: {
    sectionId: "section-mecanique",
    headingId: "heading-mecanique",
    eyebrow: "§ 04 — Mécanique · the engine",
    headline: "Detection, simulation, submission, settlement.",
    body:
      "The engine observes Base's mempool with sub-block-time latency, classifies opportunity against a strategy graph, validates outcome against a forked simulation, and submits to the sequencer along a private channel.",
    steps: [
      {
        label: "01. OBSERVATION",
        text: "Continuous observation of mempool and attested oracle lanes, normalized into a single execution clock.",
      },
      {
        label: "02. DÉTECTION",
        text: "Opportunity classification against the strategy graph; invariants enforced before any capital is touched.",
      },
      {
        label: "03. SIMULATION",
        text: "Forked execution against current state roots; slippage, fees, and liquidation surfaces computed to the basis point.",
      },
      {
        label: "04. EXÉCUTION",
        text: "Submission along private channels where required; inclusion tracked to settlement with signed receipts.",
      },
    ],
    aside:
      "Budget total par cycle · 250 ms · soit la durée d'un bloc Base.",
  },
  capital: {
    sectionId: "section-garde",
    headingId: "heading-garde",
    eyebrow: "§ 05 — Garde · the vault",
    headline: "Capital under glass.",
    body: [
      "The credit vault is organized as a tiered collateral hierarchy. Tier I assets carry the tightest haircuts and the shallowest liquidation bands; lower tiers widen both, reflecting liquidity depth and oracle confidence.",
      "Collateral factors are reputation-weighted: attested counterparties receive modest capital efficiency improvements that are bounded, published, and revocable through governance.",
      "Liquidation proceeds in a disclosed cascade: health-factor breaches trigger Dutch-style auctions tiered by asset class so that no single liquidator can monopolize the book.",
    ],
    ledger: [
      { asset: "WBTC", seuil: "85 %", frais: "5.0 bps" },
      { asset: "WETH", seuil: "85 %", frais: "5.0 bps" },
      { asset: "USDC", seuil: "90 %", frais: "2.5 bps" },
      { asset: "LP · concentrated", seuil: "70 %", frais: "8.0 bps" },
      { asset: "Réputation tier III", seuil: "55 %", frais: "12.0 bps" },
      { asset: "Réputation tier II", seuil: "40 %", frais: "18.0 bps" },
    ],
  },
  base: {
    sectionId: "section-base",
    headingId: "heading-base",
    eyebrow: "§ 06 — Substrat · why Base",
    headline: "Anchored to Coinbase. Settled in USDC.",
    paragraphs: [
      "Base offers regulatory clarity at the L2 boundary while preserving Ethereum's settlement assurances — a posture that matches how institutional desks already reason about Coinbase-adjacent infrastructure.",
      "Native USDC depth on Base reduces stablecoin basis risk across flash and credit legs, which in turn tightens oracle disagreement bands and reconciliation variance.",
      "The Coinbase sequencer profile and institutional brand alignment matter when correspondence with allocators references a single, named operator rather than an anonymous validator set.",
      "Block times and fee levels make fine-grained reconciliation events economical on-chain; the protocol can emit attestations at the frequency auditors expect without distorting execution economics.",
    ],
    stats: [
      { label: "BLOC", value: "2 s" },
      { label: "COÛT MOYEN", value: "0.4¢" },
      { label: "STABLECOIN", value: "USDC natif" },
      { label: "SÉQUENCEUR", value: "Coinbase" },
    ],
  },
  risk: {
    sectionId: "section-garanties",
    headingId: "heading-garanties",
    eyebrow: "§ 07 — Garanties · risk and safety",
    headline: "Eight surfaces. One discipline.",
    citation: "« La discipline est la première forme d'élégance. »",
    cards: [
      {
        ordinal: "I.",
        title: "Vulnérabilités de contrat",
        headline: "Two independent audits before mainnet.",
        body: "Bug bounty up to $2M. Non-upgradeable except through timelocked governance.",
        controls: "Audits · bounty · timelock",
      },
      {
        ordinal: "II.",
        title: "Réentrance",
        headline: "Checks-effects-interactions discipline.",
        body: "Cross-function reentrancy guard keyed on a transaction-scoped slot.",
        controls: "CEI · reentrancy guard",
      },
      {
        ordinal: "III.",
        title: "Manipulation d'oracle",
        headline: "Price feeds sourced from Chainlink ∩ Uniswap v3 TWAP.",
        body: "Transactions reject when the two disagree beyond fifty basis points.",
        controls: "Dual feed · 50 bps",
      },
      {
        ordinal: "IV.",
        title: "Risque MEV",
        headline: "Sensitive strategies submit through private channels.",
        body: "Slippage surfaces as a deliberate user input, never a hidden default.",
        controls: "Private channels · slippage input",
      },
      {
        ordinal: "V.",
        title: "Équité de liquidation",
        headline: "Liquidation is permissionless and tiered by collateral quality.",
        body: "No single actor can capture the cascade.",
        controls: "Permissionless · tiered",
      },
      {
        ordinal: "VI.",
        title: "Clés administratives",
        headline: "No single-signer admin key.",
        body: "Treasury and parameter changes through a 4-of-7 multisig with a timelock on user-funds-touching actions.",
        controls: "4/7 multisig · timelock",
      },
      {
        ordinal: "VII.",
        title: "Compromis d'attesteur",
        headline: "Reputation oracle signatures aggregate three of five attesters.",
        body: "Attesters are economically bonded; sustained fraud is slashable.",
        controls: "3/5 attesters · slashing",
      },
      {
        ordinal: "VIII.",
        title: "Conformité réglementaire",
        headline: "US operations under Hated By Many LLC.",
        body: "Tokenless components structured offshore. Credit product launches under accredited and institutional exemption.",
        controls: "US ops · institutional exemption",
      },
    ],
  },
  institutions: {
    sectionId: "section-institutions",
    headingId: "heading-institutions",
    eyebrow: "§ 08 — Clientèle · institutional",
    headline: "Pour les fonds, les family offices, les trésoreries.",
    columns: [
      {
        eyebrow: "01 · QUANTITATIVE FUNDS",
        title: "Programmable execution.",
        body: "The institutional API exposes flash draw, credit drawdown, and strategy routing with signed receipts suitable for fund administrators. Reconciliation reports land in Snowflake-compatible extracts.",
      },
      {
        eyebrow: "02 · FAMILY OFFICES",
        title: "Discretionary access.",
        body: "Bespoke onboarding with dedicated credit limits, discretionary fee schedules, and PIOL reconciliation reports delivered monthly to the family's counsel and custodian banks.",
      },
      {
        eyebrow: "03 · DAO TREASURIES",
        title: "On-chain governance, off-chain reporting.",
        body: "Multi-sig friendly drawdown flows, configurable reporting endpoints, and audited treasury extracts aligned to governance calendars.",
      },
    ],
    stats: [
      { label: "INSTITUTIONS ACTIVES", value: "47" },
      { label: "AUM SUIVI", value: "$612 M" },
      { label: "LIGNES DE CRÉDIT", value: "1 207" },
      { label: "RAPPORTS / MOIS", value: "3 480" },
    ],
  },
  maison: {
    sectionId: "section-maison",
    headingId: "heading-maison",
    eyebrow: "§ 09 — La maison · about the house",
    headline: "Hated By Many LLC — Maison d'exécution décentralisée.",
    paragraphs: [
      "Hated By Many LLC is the operating house behind LightRain. Established in Texas, structured for institutional counterparties, and operating under a single discipline: protocols are not products to be sold but financial primitives to be maintained. The house publishes specifications, audits, reconciliation reports, and operational metrics with the regularity of a quarterly statement from a private bank.",
      "The house operates two interlocking surfaces on one stack: on-chain execution and credit abstraction on Base, and the read-only iOS observability application through which institutional counterparties verify positions, reconciliations, and oracle attestations. Both are built and maintained by the same operating team. Both are governed under a single conflict-of-interest disclosure framework.",
      "The house's posture is intentionally narrow. It does not market consumer products. It does not run yield campaigns. It does not host airdrops. It maintains infrastructure for institutions that have read the specification, and it answers correspondence in five business days or fewer.",
    ],
    slab: [
      "HATED BY MANY LLC",
      "Texas · United States",
      "Conseil consultatif technique",
      "LightRain · PostCarrier",
      "Fondée 2024",
    ],
    citation: "« Une maison se reconnaît à la régularité de son carnet. »",
  },
  appGateway: {
    sectionId: "section-application",
    headingId: "heading-application",
    eyebrow: "§ 10 — Surveillance · the application",
    headline: "LightRain — the trust layer, on a phone.",
    body: "LightRain is the iOS application of the house. Read-only, institutional, App Store-distributed. It renders every LightRain position, reconciliation, and oracle attestation in real time. It does not sign transactions. It does not move funds. It is the eyes of the protocol, never the hands.",
    cta: { label: "Request access", href: "/#access" },
    phoneScreenTitle: "Portfolio",
  },
  dossier: {
    sectionId: "section-dossier",
    headingId: "heading-dossier",
    eyebrow: "§ 11 — Dossier · the protocol's papers",
    headline: "Specifications, audits, correspondence.",
    columns: [
      {
        title: "PROTOCOLE",
        links: [
          "Whitepaper (PDF)",
          "Smart contract architecture",
          "Strategy router specification",
          "Risk engine specification",
          "PIOL oracle specification",
          "Reputation methodology",
        ],
      },
      {
        title: "AUDITS",
        links: [
          "Trail of Bits report",
          "Runtime Verification report",
          "Spearbit review",
          "Bug bounty (Immunefi)",
          "Quarterly reconciliation reports",
          "Annual safety review",
        ],
      },
      {
        title: "PRESSE",
        links: [
          "Press kit",
          "Brand guidelines",
          "Logo and wordmark assets",
          "Approved photography",
          "Editorial contact",
          "Recent coverage",
        ],
      },
      {
        title: "RÉGULATION",
        links: [
          "Hated By Many LLC corporate filings",
          "Legal disclosures",
          "Privacy notice",
          "Terms of service",
          "Compliance contact",
          "Regulator inquiries",
        ],
      },
    ],
    closing: "« Tout est public. Tout est daté. Tout est signé. »",
  },
  header: {
    nav: [
      { label: "Thèse", href: "/la-these#section-these" },
      { label: "Pratique", href: "/la-pratique#section-pratique" },
      { label: "Mécanique", href: "/la-mecanique#section-mecanique" },
      { label: "Garanties", href: "/les-garanties#section-garanties" },
      { label: "Maison", href: "/la-maison#section-maison" },
      { label: "Dossier", href: "/le-dossier#section-dossier" },
    ],
    cta: { label: "Download App", href: "/#overview" },
  },
  sectionPortals: [
    {
      href: "/la-these#section-these",
      navShort: "Thèse",
      title: "La Thèse",
      tagline: "Deux régimes de capital composés sur un seul rail d'exécution.",
      roman: "I",
    },
    {
      href: "/la-pratique#section-pratique",
      navShort: "Pratique",
      title: "La Pratique",
      tagline: "Flash atomique et crédit durable, dessinés en élévation.",
      roman: "II",
    },
    {
      href: "/la-mecanique#section-mecanique",
      navShort: "Mécanique",
      title: "La Mécanique",
      tagline: "Détection, simulation, soumission, règlement — le moteur.",
      roman: "III",
    },
    {
      href: "/les-garanties#section-garanties",
      navShort: "Garanties",
      title: "Les Garanties",
      tagline: "Huit surfaces de risque, une discipline de maison.",
      roman: "IV",
    },
    {
      href: "/la-maison#section-maison",
      navShort: "Maison",
      title: "La Maison",
      tagline: "Hated By Many LLC — intention, carnet, et correspondance.",
      roman: "V",
    },
    {
      href: "/le-dossier#section-dossier",
      navShort: "Dossier",
      title: "Le Dossier",
      tagline: "Spécifications, audits, presse, et cadre réglementaire.",
      roman: "VI",
    },
  ],
  footer: {
    slabTitle: "LightRain.",
    slabSubtitle:
      "Société de liquidité décentralisée · Maison Hated By Many LLC",
    columns: {
      A: {
        title: "PROTOCOLE",
        links: [
          "Whitepaper",
          "Architecture",
          "Strategy router",
          "Risk engine",
          "PIOL oracle",
          "Reputation oracle",
          "Credit vault",
          "Fee controller",
          "Flash loan executor",
          "Smart contract index",
          "Deployment addresses",
          "Aave integration",
          "Uniswap adapters",
          "Curve adapters",
          "Balancer adapters",
          "GMX adapters",
          "Aerodrome on Base",
        ],
      },
      B: {
        title: "APPLICATION",
        links: [
          "LightRain (iOS)",
          "TestFlight",
          "LightRain pour iPad",
          "LightRain pour Mac",
          "API institutionnelle",
          "WebSocket flux",
          "APNs alerts",
          "Portfolio surface",
          "Strategy analytics",
          "Oracle transparency",
          "Audit trail viewer",
          "SwiftUI release notes",
          "Application changelog",
        ],
      },
      C: {
        title: "MAISON",
        links: [
          "À propos de Hated By Many LLC",
          "Conseil consultatif",
          "Équipe technique",
          "Recrutement",
          "Bourse de stages",
          "Bureau Austin",
          "Bureau Carrollton",
          "Partenaires audit",
          "Partenaires juridique",
          "Conseil d'administration",
          "Note de gouvernance",
          "Note d'intention",
        ],
      },
      D: {
        title: "RECHERCHE",
        links: [
          "Note d'intention",
          "Mémoire technique",
          "Risk papers",
          "Backtests publiés",
          "Méthodologie de réputation",
          "Méthodologie PIOL",
          "Comparaison Aave",
          "Comparaison Compound",
          "Comparaison Morpho",
          "Économie du protocole",
          "Modèle de frais",
        ],
      },
      E: {
        title: "RÉGULATION",
        links: [
          "Conformité US",
          "Conformité EU",
          "MiCA",
          "BSA / FinCEN",
          "OFAC screening",
          "Travel Rule",
          "KYC institutionnel",
          "KYB process",
          "Legal",
          "Investor Relations",
          "Privacy notice",
          "Terms of service",
          "Cookie policy",
          "Whistleblower",
        ],
      },
      F: {
        title: "CORRESPONDANCE",
        links: [
          "press@lightra.in",
          "partnerships@lightra.in",
          "institutions@lightra.in",
          "legal@lightra.in",
          "security@lightra.in",
          "disclosure@lightra.in",
          "careers@lightra.in",
          "investors@lightra.in",
          "regulators@lightra.in",
          "Hated By Many LLC",
          "Texas",
          "United States",
        ],
      },
    },
    frieze:
      "BASE · ARBITRUM (Q4) · SOLANA (Q1) · ETHEREUM (mainnet) · OPTIMISM · ZKsync",
    imprintLeft:
      "© 2026 Hated By Many LLC. Tous droits réservés. LightRain is a registered trademark of Hated By Many LLC.",
    imprintRight: "Version 2026.05 · build live · Texas, USA",
  },
} as const;

export type HomepageCopy = typeof homepageCopy;
